openapi: 3.0.2
info:
  description: Two prototype Knowledge Objects in R language are activated to provide REST API leveraging the R package of 'plumber'
  title: Prototype Knowledge Objects activated in RStudio
  version: 1.0.0
paths:
  /99999-hepc/predict:
    $ref: 'shelf/99999-hepc/service.yaml#/paths/~199999-hepc~1predict'
  /hello-world/welcome:
    $ref: 'shelf/hello-world/service.yaml#/paths/~1hello-world~1welcome'
